### ISSUE TITLE
uninitialized constant BaseController::OutputFilter

### ISSUE THREAD

**Issue by galenking** [svenfuchs/adva_cms#1]
Hi guys,

When I try to run the rake tasks, I get this error every time: "uninitialized constant BaseController::OutputFilter"

Any ideas?

Cheers,

Galen

**Comment by m3talsmith** [comment]
Yeah I ran in to this a few days back. It looks like the load_path is off some how. I think it might be a race condition because the module and class definitely exist.

**Comment by m3talsmith** [comment]
Add this after line 5 of engines/adva_cms/lib/tasks/adva_cms.rake

<pre>
ENV['plugins'] = %w(adva_cells).join(',')
</pre>

**Comment by galenking** [comment]
Awesome, that did it. Thanks.
