### ISSUE TITLE
[adva_newsletter] "no such file to load -- addressable/uri" on rake adva:install engines=adva_newsletter

### ISSUE THREAD

**Issue by m3talsmith** [svenfuchs/adva_cms#2]
When doing a:

<pre>rake adva:install engines=adva_newsletter</pre>

The rake will fail with "no such file to load -- addressable/uri". There is a missing gem "addressable" that should be integrated somehow. This is important as it trips up a simple adva:install:all besides the obvious single engine install. This also trips an adva:install plugins=all . The simple answer is to install the gem locally, but this fails to bring in the ease and nature of keeping engines easily installable and removable. Perhaps we should think about a hook that checks each engines environment.rb for required engines, installing them, before installing the engine.

**Comment by mseppae** [comment]
Late answer but anyway,

addressable is now removed from adva_newsletter sho this problem should not exist anymore.

**Comment by m3talsmith** [comment]
Late answer back .. Thanks :)
