### ISSUE TITLE
no such file to load -- ruby_pants 

### ISSUE THREAD

**Issue by mischa** [svenfuchs/adva_cms#3]
this can be fixed by changing 

  config.plugin_gem 'rubypants', :version => '~> 0.2.0', :lib => 'ruby_pants'

to 

  config.plugin_gem 'rubypants', :version => '~> 0.2.0', :lib => 'rubypants'

**Comment by mseppae** [comment]
Hi Mischa,

I cannot reproduce the original error.

Here is my console log - as you see with the fix it breaks for me:

http://pastie.org/private/z2gzwlfgpkxbr4cojp47g

-- Marko

**Comment by mseppae** [comment]
problem detected and solved

**Comment by mischa** [comment]
great, thanks!
