### ISSUE TITLE
Proper decode of cookie values

### ISSUE THREAD

**Issue by boof** [svenfuchs/adva_cms#6]
Ok, I'm new to the adva CMS so it took me some time to figure this out. But since my last name is Aßmann it really bothered me. :)

in adva_cms/engines/adva_cms/public/javascripts/adva_cms/application.js at line 4 you try to unescape the values from a cookie. It seems Rails uses URI encode for values stored in cookies so you need to call decodeURIComponent instead of unescape.

Regards
Florian Aßmann !(Florian AÃmann :)

**Comment by svenfuchs** [comment]
Hi Florian,

thanks for pointing this out. The proposed fix doesn't seem to work for me though:

http://skitch.com/svenfuchs/n8fxw/adva-cms-cookie-encoding

Any further ideas?

**Comment by boof** [comment]
Ah, my fail. Forgot that I changed authentication_user.rb, too. I've wrapped user.name in a CGI.escape before assignment to cookies[:uname]. This works for me in FF 3.5.5 and Safari 4.0.3.

**Comment by svenfuchs** [comment]
Ah, alright, pushed: http://github.com/svenfuchs/adva_cms/commit/c139e0ef0bfa380061ad2c045798df4d5658da91

Does that work for you?
